name: dslink_html5
description: HTML5 DSLink
dependencies:
  core_elements: ">=0.7.0 <0.8.0"
  paper_elements: ">=0.7.0 <0.8.0"
  polymer: ">=0.16.1+3 <0.17.0"
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
transformers:
 - polymer:
     include: web/index.html
